apiVersion: v1
kind: Service
metadata:
  name: financial-react-service
  namespace: financial
  labels:
    app: financial-app
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  selector:
    app: financial-react-app
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: LoadBalancer