apiVersion: v1
kind: Service
metadata:
  name: financial-python-service
  namespace: financial
  labels:
    app: financial-app
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  selector:
    app: financial-python-server
  type: LoadBalancer
  ports:
  - name: financial-python-service
    port: 5000
    targetPort: 5000
    protocol: TCP