apiVersion: v1
kind: Service
metadata:
  name: financial-go-service
  namespace: financial
  labels:
    app: financial-app
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  selector:
    app: financial-go-server
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer